language: python
matrix:
  include:
    - os: linux
      env: RUN_TESTS="true" WITH_PYTHON="3.6"
    - os: linux
      env: RUN_TESTS="true" WITH_PYTHON="3.7"
    - os: osx
      sudo: required
      language: generic
      env: RUN_TESTS="true" WITH_PYTHON="3.6"
    - os: osx
      sudo: required
      language: generic
      env: RUN_TESTS="true" WITH_PYTHON="3.7"
before_cache:
  - rm -f /home/travis/.cache/pip/log/debug.log
cache:
  apt: true
  directories:
  - /home/travis/miniconda3
  - /home/travis/.cache/pip
notifications:
  email: false
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - libboost1.55-all-dev
before_install:
  - source build_tools/travis/install.sh
  - if [[ "$WITH_PYTHON" == "3.6" ]]; then source activate testenv3; elif [[ "$WITH_PYTHON" == "2.7" ]]; then source activate testenv2; fi
install: bash scripts/install_requirements.sh
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo unlink /usr/bin/g++; sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi
  - bash scripts/compile_engines.sh
script: bash build_tools/travis/test_script.sh
