language: python
group: travis_latest

git:
  depth: 25
  quiet: true

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        - RUN_TESTS="true" WITH_PYTHON="3.7"
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - RUN_TESTS="true" WITH_PYTHON="3.7"
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - RUN_TESTS="true" WITH_PYTHON="3.7"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"
        - RUN_TESTS="true" WITH_PYTHON="3.7"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
        - RUN_TESTS="true" WITH_PYTHON="3.7"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
        - RUN_TESTS="true" WITH_PYTHON="3.7"

before_cache:
  - rm -f /home/travis/.cache/pip/log/debug.log

cache:
  directories:
  - /home/travis/miniconda3
  - /home/travis/.cache/pip

notifications:
  email: false

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang
      - g++
      - gcc
      - libboost1.71-all-dev

before_install:
  - eval "${MATRIX_EVAL}"
  - source build_tools/travis/install.sh
  - source activate testenv37

install: bash scripts/install_requirements.sh

before_script:
  - bash scripts/compile_engines.sh

script: bash build_tools/travis/test_script.sh
